### ISSUE TITLE
Trouble connecting via ProxyCommand

### ISSUE THREAD

**Issue by LinqLover** [sganis/golddrive#1]
My `.ssh/config` looks like this:

```.ssh/config
Host myhost
  HostName 172.18.123.45
  User myname
  ProxyCommand ssh.exe -W %h:%p mysshjump

Host mysshjump
  HostName my.hostname.com
  User user.name
```

Using OpenSSH, I can connect to `myhost` by executing:

```powershell
ssh myhost
```

As I ssh-copied my identity to `myhost`, but not to `mysshjump`, after executing the latest command, I am asked for `user.name@my.hostname.com's password`. After entering it, I am successfully connected to `myhost`.

So, now I am trying to achieve the same via golddrive. So I set it up as the screenshot shows (`z:` being an unassigned network letter), but unfortunately, I am not asked for any password but the UI does not change even when I wait a few minutes:

![image](https://user-images.githubusercontent.com/38782922/76760517-16937180-678e-11ea-81e4-f2d88dc057d3.png)

However, if I try to connect to a different `user@host`, golddrive asks me for the password and I can establish a connection.

So my question is: Am I right that this is a bug? And is there any option to set up the connection as described above? Unfortunately, `mysshjump` does not allow to store my ssh identity, so I need to enter a password each time.

**Comment by sganis** [comment]
Hi Chistoph,

Golddrive does not support password authentication, only ssh keys. If your server asks for password, it is not going to work. The user interface asks for password to setup keys for the first time, then it invokes a command line service that uses key authentication. 

Password authentication is planned for the future, though. 

San.

**Comment by LinqLover** [comment]
Hi San, great to hear this! I'm really looking forward to this f(ea|u)ture. :-)

**Comment by sganis** [comment]
> My `.ssh/config` looks like this:
> 
> ```
> Host myhost
>   HostName 172.18.123.45
>   User myname
>   ProxyCommand ssh.exe -W %h:%p mysshjump
> 
> Host mysshjump
>   HostName my.hostname.com
>   User user.name
> ```
> 
> Using OpenSSH, I can connect to `myhost` by executing:
> 
> ```powershell
> ssh myhost
> ```
> 
> As I ssh-copied my identity to `myhost`, but not to `mysshjump`, after executing the latest command, I am asked for `user.name@my.hostname.com's password`. After entering it, I am successfully connected to `myhost`.
> 
> So, now I am trying to achieve the same via golddrive. So I set it up as the screenshot shows (`z:` being an unassigned network letter), but unfortunately, I am not asked for any password but the UI does not change even when I wait a few minutes:
> 
> ![image](https://user-images.githubusercontent.com/38782922/76760517-16937180-678e-11ea-81e4-f2d88dc057d3.png)
> 
> However, if I try to connect to a different `user@host`, golddrive asks me for the password and I can establish a connection.
> 
> So my question is: Am I right that this is a bug? And is there any option to set up the connection as described above? Unfortunately, `mysshjump` does not allow to store my ssh identity, so I need to enter a password each time.
