### ISSUE TITLE
Enable use without initial password authentication

### ISSUE THREAD

**Issue by bersbersbers** [sganis/golddrive#2]
My server does not allow password-based authentication, so I am unable to connect to even have keys generated.
Error message is
> Password is required to connect to user@host:22.
> SSH keys will be generated and used in future conections.

Maybe my problem is a more hidden one, but initial connection through the GUI fails with the above error although ssh.exe on its own is able to connect just fine:
```
C:\Program Files\Golddrive>.\ssh.exe host
Last login: Wed Jul  1 13:34:22 2020 from IP
Have a lot of fun...
```

So ideally, there should not be a need to request a password or generate a key, it's all there.

**Comment by sganis** [comment]
It's a good idea
