### ISSUE TITLE
SSH Agent support

### ISSUE THREAD

**Issue by itsTyrion** [sganis/golddrive#6]
Hi, I'm coming from the sshfs-win issue thread about using an SSH agent - I'm trying to use 1password, which replaced the named pipe Windows' native SSH Agent Service normally uses (`\\.\pipe\openssh-ssh-agent`) ([source](https://developer.1password.com/docs/ssh/get-started/#step-3-turn-on-the-1password-ssh-agent))  instead of creating a socket.

Works perfectly to open a ssh connection (PowerShell/cmd/Golddrive Terminal), but doesn't seem to work with Golddrive itself. Is this feature missing or did I overlook it?

**Comment by sganis** [comment]
It is a missing feature. Golddrive only works with ssh keys.

**Comment by sganis** [comment]
Closing as this feature will not be implemented any time soon

**Comment by sganis** [comment]
.
